### ISSUE TITLE
Correctly handle Q values.

### ISSUE THREAD

**Issue by otac0n** [benfoster/Fabrik.Common#9]
The current implementation is incorrect, when dealing with Q values for the `Accept-Encoding` header.

For example, with this request...

```
GET /foo HTTP/1.1
Accept-Encoding: gzip;q=0
```

...GZip should NEVER be chosen.  And this one...

```
GET /foo HTTP/1.1
Accept-Encoding: gzip;q=0.5, deflate;q=1
```

... should choose deflate.

See: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3

Fortunately, this should be an easy fix (since your code is very well built); just replace lines 28-30 of CompressionHandler.cs with something like this:

```
var compressor = (from a in request.Headers.AcceptEncoding
                  let q = a.Quality ?? 1.0
                  where q > 0
                  join c in Compressors on a.Value.ToUpperInvariant() equals c.EncodingType.ToUpperInvariant()
                  orderby q descending
                  select c).FirstOrDefault();
```

Now, this still doesn't get it to 100%, because `identity` is a value that is allowed, which means no compression.  I'm not sure what the best way to special-case that is, but I leave that as an exercise for the real developers. ;)

**Comment by benfoster** [comment]
Thanks for logging this issue. It has been fixed on the dev branch. I should release a new NuGet package in the next few weeks.

Since a `Accept-Encoding: identity` (or essentially sending no `Accept-Encoding` header) will not match any compressor, the content will not be compressed which I believe meets the requirements of the specification. It does not state that the identity encoding supersedes any other (other than if it has a higher quality) in which case I believe this implementation is acceptable. Let me know if you don't agree.

**Comment by otac0n** [comment]
Well, this doesn't cover this case:

```
Accept-Encoding: gzip;q=0.5, identity;q=1
```

But, since gzip is _acceptable_, (which is what the greater-than-zero filtering does), it is not a violation of the spec to transmit using gzip.

That is, you are 100% in-line with the spec, with the caveat that we will ignore the client's preference if they explicitly list identity as higher than gzip or compress.

**Comment by benfoster** [comment]
I can live with that. Since in most cases the client _will_ have control over the headers it would be pretty pointless for them to send a valid compression encoding and `identity` - they may as well omit the header all together. You could of course create a `IdentityCompressor` that doesn't touch the response stream but I'll leave this up to you :)
